---
title: "Women in the workforce"
author: "Teresa Chen"
date: "3/8/2019"
output: html_document
---

```{r setup, include=FALSE}
library(rio)

library(extrafontdb)
library(Rttf2pt1)
extrafont::font_import()
extrafont::loadfonts(device="win")
extrafont::fonttable()

library(tidyverse)
library(hrbrthemes)

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      error = TRUE)
```

```{r importdata}

jobs_gender <- import("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv", 
                      setclass = "tbl_df")
earnings_female <- import("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv",
                          setclass = "tbl_df") 
employed_gender <- import("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv",
                          setclass = "tbl_df") 

```


```{r plot1, fig.width=12, fig.height=5}


# skimr::skim(earnings_female)

earnings_female %>% 
  filter(group != "Total, 16 years and older") %>% 
  ggplot(aes(x = Year, y = group, fill = percent)) +
    geom_tile(color = "white") +
    scale_x_continuous(expand = c(0, 0), breaks = seq(1980, 2011, 5)) +
    coord_equal() +
    scale_fill_viridis_c() +
    theme_ipsum_tw()+
    labs(title = "Femal Salary: It is better nowadays, but certainly can be better. ",
         subtitle = "",
         fill = "% of male salary",
         y = "",
         caption = "Bureau of Labor Statistics and the Census Bureau")
```

```{r fig.height=10, fig.width=20}

jobs_gender %>% 
  mutate(salary_percent = total_earnings_female/total_earnings_male) %>% 
  filter(!is.na(salary_percent)) %>%
  group_by(year) %>% 
  arrange(salary_percent) %>% 
  slice(1:5) %>% 
  ungroup() %>% 
  ggplot(aes(x = fct_reorder(occupation, salary_percent), 
             y = salary_percent)) +
    ggalt::geom_lollipop(point.colour = "red",
                         point.size = 5) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                       expand = c(0.01, 0.01)) +
    coord_flip() +
    facet_grid(year~., scales = "free_y", space = "free_y") +
    theme_minimal(base_size = 20) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.y = element_blank()) +
    labs(x = "",
         y = "% of male salary")

```


```{r fig.height=10, fig.width=20}

jobs_gender %>% 
  mutate(salary_percent = total_earnings_female/total_earnings_male) %>% 
  filter(!is.na(salary_percent)) %>%
  group_by(year) %>% 
  arrange(desc(salary_percent)) %>% 
  slice(1:5) %>% 
  ungroup() %>% 
  ggplot(aes(x = fct_reorder(occupation, salary_percent), 
             y = salary_percent)) +
    ggalt::geom_lollipop(point.colour = "steelblue",
                         point.size = 5) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                       expand = c(0.01, 0.01)) +
    coord_flip() +
    facet_grid(year~., scales = "free_y", space = "free_y") +
    theme_minimal(base_size = 20) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.y = element_blank()) +
    labs(x = "",
         y = "% of male salary")

```




```{r fig.height=7, fig.width=11}

jobs_gender %>% 
  mutate(salary_percent = total_earnings_female/total_earnings_male) %>% 
  filter(!is.na(salary_percent)) %>%
  dplyr::select(year, occupation, salary_percent) %>% 
  spread(year, salary_percent) %>% 
  mutate(change = `2016` - `2013`) %>%
  arrange(change) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = `2013`, xend = `2016`, 
             y = fct_reorder(occupation, change, .desc = TRUE), group = occupation)) +
    ggalt::geom_dumbbell(size=3, 
                         color="#e3e2e1", 
                         colour_x = "#CD5C5C", colour_xend = "CORNFLOWERBLUE",
                dot_guide = TRUE, dot_guide_size=0.25) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = c(0.5, 1, 1.5, 2, 2.5, 3)) +
  geom_vline(xintercept = 1) +
  # theme_minimal(base_size = 17) +
  theme_ipsum_tw()+
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(x = "Female Salary (% of male salary)", 
       y = "",
       subtitle = "Top 10 occupations with largest negative growth",
       title = "Female Salary in 2013 and 2016" ) +
  geom_text(aes(label = "2016", x = 0.5, y = 10.5), color = "CORNFLOWERBLUE") +
  geom_text(aes(label = "2013", x = 3.2, y = 10.5), color = "#CD5C5C") 
```


`

